- import_role:
    name: jail
    tasks_from: jail_setup

- name: Install aggro
  shell: pkg install -y -r poudriere aggro
  register: _aggro_install
  changed_when: "'Installing' in _aggro_install.stdout"

- name: Deploy aggro env file
  template:
    src: "{{ jail_role_dir }}/templates/aggro.env.j2"
    dest: /usr/local/etc/aggro.env
    owner: root
    group: wheel
    mode: "0600"
  notify: Restart aggro

- name: Deploy Aggrofile
  template:
    src: "{{ jail_role_dir }}/templates/Aggrofile.j2"
    dest: /usr/local/etc/Aggrofile
    owner: root
    group: wheel
    mode: "0644"
  notify: Restart aggro

- import_role:
    name: jail
    tasks_from: jail_launch
