all:
  children:
    servers:
      hosts:
        pursotin:
          host_roles:
            - host
            - host_prod
          nic_lan: igc0
          nic_wan: igc1
          arch: amd64/amd64
          lan_ipv4_gateway: "192.168.0.1"
          lan_ipv4_cidr: "192.168.0.10/16"
          is_prod: true
    jails:
      vars:
        ansible_jail_host: pursotin
        jail_delegate_host: pursotin
        jail_lan_cidr: "192.168.2.0/16"
        jail_lan_offset: 0
        ssl_enabled: true
        is_prod: true
