userland: "15.1-RELEASE"

zfs:
  - name: komga_data

nullfs:
  - src: komga_data
    dst: /var/db/komga
  - src: storage/media/manga
    dst: /mnt/manga

pkg:
  - poppler-utils
  - zip

pkg_custom:
  - komga

services:
  - komga
