- import_role:
    name: jail
    tasks_from: jail_setup

- name: Install expense-tracker
  shell: pkg install -y -r poudriere expense-tracker
  register: _spliit_install
  changed_when: "'Installing' in _spliit_install.stdout"

- name: Configure expense_tracker
  community.general.sysrc:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: expense_tracker_base_url, value: "https://spliit.jan.systems" }
    - { name: expense_tracker_port, value: "80" }

- import_role:
    name: jail
    tasks_from: jail_launch
