userland: "14.3-RELEASE"
devfs_ruleset: 5

jail_conf_options:
  - "allow.raw_sockets"
  - "allow.sysvipc"

pkg:
  - postgresql18-server

services: []

pg_users:
  - spliit
  - immich

pg_databases:
  - { name: spliit, owner: spliit }
  - { name: immich, owner: immich }
