userland: "15.0-RELEASE"
devfs_ruleset: 5

zfs:
  - name: zroot/jails/volumes/postgres_data
    mountpoint: /var/db/postgres
    owner: "770"
    group: "770"
    mode: "0755"

jail_conf_options:
  - "allow.raw_sockets"
  - "allow.sysvipc"

pkg:
  - postgresql18-server
  - postgresql18-pgvector

services:
  - postgresql

pg_users:
  - immich

pg_databases:
  - name: immich
    owner: immich
    init: "CREATE EXTENSION IF NOT EXISTS vector; ALTER EXTENSION vector UPDATE;"
