- name: "Check if jail directory for {{ jail.name }} exists"
  shell: zfs list -o name | grep -Fxq "zroot/jails/containers/{{ jail.name }}"
  failed_when: false
  changed_when: false
  register: check_jail_directory

- name: "ZFS clone snapshot to jail directory for {{ jail.name }}"
  shell: zfs clone zroot/jails/templates/{{ jail_userland_version }}@base "zroot/jails/containers/{{ jail.name }}"
  when: check_jail_directory.rc != 0

- name: "Check if jail {{ jail.name }} is running"
  shell: jls -j "{{ jail.name }}"
  failed_when: false
  changed_when: false
  register: check_jail_active

- name: "(Re)start jail {{ jail.name }}"
  shell: service jail restart "{{ jail.name }}"
  when: check_jail_active.rc != 0
