- name: Ensure /usr/local/etc/rc.d/ exists
  file:
    path: /usr/local/etc/rc.d/
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: Add zpool_gpt_labels rc.d service
  template:
    src: usr_local_etc_rc.d_zpool_gpt_labels.j2
    dest: /usr/local/etc/rc.d/zpool_gpt_labels
    owner: root
    group: wheel
    mode: "0755"

- name: Enable and start zpool_gpt_labels
  service:
    name: zpool_gpt_labels
    enabled: true
    state: started

- name: Install smartd
  package:
    name: smartmontools
    state: present

- name: Configure smartd.conf
  template:
    src: usr_local_etc_smartd.conf.j2
    dest: /usr/local/etc/smartd.conf
    owner: root
    group: wheel
    mode: "0644"

- name: Enable and start smartd
  service:
    name: smartd
    enabled: true
    state: started
