- import_role:
    name: jail
    tasks_from: jail_setup

- name: Add log extension to mime.types
  shell: sed -i '' -E 's|text/plain[\t\ ]*txt|text/plain txt log|g' /usr/local/etc/nginx/mime.types
  changed_when: false

- import_role:
    name: jail
    tasks_from: jail_launch
