userland: "15.1-RELEASE"

zfs:
  - name: forge_repos
    mode: "0755"
  - name: forge_config
    mode: "0755"

nullfs:
  - src: forge_repos
    dst: /var/db/repos
  - src: forge_config
    dst: /var/db/forge-config

forge_users:
  - name: jan
    uid: 2000
    authorized_keys: "{{ forge_authorized_keys }}"

pkg:
  - git
  - cgit
  - fcgiwrap
  - nginx
  - highlight
  - py312-docutils
  - py312-markdown
  - py312-pygments
  - groff

services:
  - sshd
  - nginx
  - fcgiwrap
  - cron

sysrc:
  - name: fcgiwrap_socket_owner
    value: "www"
  - name: fcgiwrap_socket_group
    value: "www"
  - name: fcgiwrap_user
    value: "www"
  - name: fcgiwrap_group
    value: "www"
