userland: "15.1-minimal-jail"

zfs:
  - name: forge_repos
    owner: "1000"
    group: "1000"
    mode: "0755"

nullfs:
  - src: forge_repos
    dst: /var/db/repos

pkg:
  - FreeBSD-ssh
  - git
  - cgit
  - fcgiwrap
  - nginx
  - highlight
  - py312-docutils
  - py312-markdown
  - py312-pygments
  - groff

services:
  - sshd
  - nginx
  - fcgiwrap
  - cron

rc_conf: |
  fcgiwrap_socket_owner="www"
  fcgiwrap_socket_group="www"
  fcgiwrap_user="www"
  fcgiwrap_group="www"
