- import_role:
    name: jail
    tasks_from: jail_setup

- name: Install hommabot
  shell: pkg install -y -r poudriere hommabot
  register: _hommabot_install
  changed_when: "'Installing' in _hommabot_install.stdout"

- name: Deploy bot token file
  copy:
    content: "{{ hommabot_telegram_bot_token }}"
    dest: /usr/local/etc/hommabot.token
    owner: root
    group: wheel
    mode: "0600"
  no_log: true
  notify: Restart hommabot

- import_role:
    name: jail
    tasks_from: jail_launch
