userland: "15.1-minimal-jail"

zfs:
  - name: spliit_data

nullfs:
  - src: spliit_data
    dst: /var/db/expense-tracker

pkg_custom:
  - expense-tracker

services:
  - expense_tracker

rc_conf: |
  expense_tracker_base_url="https://spliit.jan.systems"
  expense_tracker_port="80"
