- import_role:
    name: jail
    tasks_from: jail_setup

- name: Create php-fpm socket directory
  file:
    path: /var/run/php
    state: directory
    owner: www
    group: www
    mode: "0755"

- import_role:
    name: jail
    tasks_from: jail_launch
