- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart cron
  service:
    name: cron
    state: restarted

- name: Restart zfs_exporter
  service:
    name: zfs_exporter
    state: restarted
