userland: "15.1-minimal-jail"

zfs:
  - name: homepage_www
  - name: homepage_agate_tls
    owner: "80" # www
    group: "80"
  - name: homepage_gemini

nullfs:
  - src: homepage_www
    dst: /var/www
  - src: homepage_agate_tls
    dst: /usr/local/etc/agate/tls
  - src: homepage_gemini
    dst: /var/gemini

pkg:
  - pcre2
  - nginx
  - rsync
  - bash
  - agate

files:
  - src: usr_local_etc_nginx_nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf

services:
  - nginx
  - agate

dirs:
  - /var/log/agate

rc_conf: |
  agate_hostname="jan.systems"
  agate_content="/var/gemini"
  agate_certs="/usr/local/etc/agate/tls"
  agate_logfile="/var/log/agate/agate.log"
  agate_addr="0.0.0.0"
  agate_port="1965"
  agate_env="RUST_LOG=error"
