userland: "15.1-RELEASE"

zfs:
  - name: homepage_www
  - name: homepage_agate_tls
    owner: "80" # www
    group: "80"
  - name: homepage_gemini

nullfs:
  - src: homepage_www
    dst: /var/www
  - src: homepage_agate_tls
    dst: /usr/local/etc/agate/tls
  - src: homepage_gemini
    dst: /var/gemini

pkg:
  - pcre2
  - nginx
  - rsync
  - bash
  - agate

files:
  - src: usr_local_etc_nginx_nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf

services:
  - nginx
  - agate

dirs:
  - /var/log/agate

sysrc:
  - name: agate_hostname
    value: "jan.systems"
  - name: agate_content
    value: "/var/gemini"
  - name: agate_certs
    value: "/usr/local/etc/agate/tls"
  - name: agate_logfile
    value: "/var/log/agate/agate.log"
  - name: agate_addr
    value: "0.0.0.0"
  - name: agate_port
    value: "1965"
