userland: "15.1-RELEASE"
devfs_ruleset: 4

jail_conf_options:
  - "allow.raw_sockets"
  - "allow.mlock"

zfs:
  - name: dl_sonarr
    owner: 351
    group: 351
  - name: dl_radarr
    owner: 352
    group: 352
  - name: dl_lidarr
    owner: 356
    group: 356
  - name: dl_prowlarr
    owner: 359
    group: 359

nullfs:
  - src: storage
    dst: /mnt/storage
  - src: dl_sonarr
    dst: /usr/local/sonarr
  - src: dl_radarr
    dst: /usr/local/radarr
  - src: dl_lidarr
    dst: /usr/local/lidarr
  - src: dl_prowlarr
    dst: /usr/local/prowlarr

pkg:
  - transmission-daemon
  - transmission-web
  - transmission-cli
  - nzbget
  - yt-dlp
  - sonarr
  - radarr
  - lidarr
  - prowlarr
  - ffmpeg
  - unrar
  - wireguard-tools
  - git
  - bash
  - fd-find
  - shntool
  - cuetools
  - vorbisgain
  - flac

services:
  - wg_random_tunnel
  - transmission
  - nzbget
  - prowlarr
  - sonarr
  - radarr
  - lidarr
