userland: "15.1-RELEASE"
devfs_ruleset: 4

jail_conf_options:
  - "allow.raw_sockets"
  - "allow.mlock"

nullfs:
  - src: /usr/local/jails/volumes/storage
    dst: /mnt/storage

zfs:
  - name: zroot/jails/volumes/dl_sonarr
    mountpoint: /usr/local/sonarr
    owner: 351
    group: 351
  - name: zroot/jails/volumes/dl_radarr
    mountpoint: /usr/local/radarr
    owner: 352
    group: 352
  - name: zroot/jails/volumes/dl_lidarr
    mountpoint: /usr/local/lidarr
    owner: 356
    group: 356
  - name: zroot/jails/volumes/dl_prowlarr
    mountpoint: /usr/local/prowlarr
    owner: 359
    group: 359

pkg:
  - transmission-daemon
  - transmission-web
  - transmission-cli
  - nzbget
  - yt-dlp
  - sonarr
  - radarr
  - lidarr
  - prowlarr
  - ffmpeg
  - unrar
  - wireguard-tools
  - git
  - bash
  - shntool
  - cuetools
  - vorbisgain
  - flac

services:
  - wg_random_tunnel
  - transmission
  - nzbget
  - prowlarr
  - sonarr
  - radarr
  - lidarr
