userland: "15.1-RELEASE"

zfs:
  - name: plex_data
    owner: 972
    group: 972
    mode: 755

nullfs:
  - src: plex_data
    dst: /usr/local/plexdata
  - src: storage/media
    dst: /mnt/media

pkg_custom:
  - plexmediaserver

services:
  - plexmediaserver
