userland: "15.0-RELEASE"

zfs:
  - name: zroot/jails/volumes/plex_data
    mountpoint: /usr/local/plexdata
    owner: 972
    group: 972
    mode: 755

nullfs:
  - src: /usr/local/jails/volumes/storage/media
    dst: /mnt/media

services:
  - plexmediaserver
