userland: "15.1-RELEASE"

zfs:
  - name: zroot/jails/volumes/freshrss_data
    mountpoint: /var/db/freshrss
    owner: "80"
    group: "80"

pkg:
  - nginx

pkg_custom:
  - freshrss-php84

files:
  - src: usr_local_etc_nginx_nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
  - src: usr_local_etc_php_fpm.d_www.conf
    dest: /usr/local/etc/php-fpm.d/www.conf

services:
  - nginx
  - php_fpm
