userland: "15.1-RELEASE"

zfs:
  - name: goaccess_data

nullfs:
  - src: goaccess_data
    dst: /var/db/goaccess
  - src: ingress_logs
    dst: /mnt/nginx_logs

pkg:
  - goaccess
  - pcre2
  - nginx

services:
  - nginx

files:
  - src: usr_local_etc_nginx_nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
  - src: usr_local_bin_gen_goaccess.sh
    dest: /usr/local/bin/gen_goaccess.sh
    mode: "0755"
  - src: etc_crontab
    dest: /etc/crontab
