userland: "15.0-RELEASE"

zfs:
  - name: zroot/jails/volumes/aggro_data
    mountpoint: /var/db/aggro

pkg:
  - python311
  - py311-pip
  - py311-setuptools
  - py311-build
  - py311-installer
  - py311-wheel
  - libxml2
  - libxslt

services:
  - aggro
