userland: "15.0-RELEASE"

zfs:
  - name: zroot/jails/volumes/aggro_data
    mountpoint: /var/db/aggro

pkg:
  - python312
  - py312-pip
  - py312-setuptools
  - py312-build
  - py312-installer
  - py312-wheel
  - python
  - libxml2
  - libxslt

pkg_custom:
  - aggro

services:
  - aggro
