- import_role:
    name: jail
    tasks_from: jail_setup

- name: Set thelounge user and group
  community.general.sysrc:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: thelounge_user, value: root }
    - { name: thelounge_group, value: wheel }

- name: Deploy thelounge config
  copy:
    src: "{{ jail_role_dir }}/files/config.js"
    dest: /var/db/thelounge/config.js
    owner: root
    group: wheel
    mode: "0644"
  notify: Restart thelounge

- import_role:
    name: jail
    tasks_from: jail_launch
