userland: "15.1-RELEASE"
immich_version: "v3.0.3"

dirs:
  - /usr/local/etc/rc.d

oci_images:
  - name: immich-server
    image: "ghcr.io/immich-app/immich-server:{{ immich_version }}"
    check_path: /usr/src/app/server/dist/main.js
  - name: immich-ml
    image: "ghcr.io/immich-app/immich-machine-learning:{{ immich_version }}"
    check_path: /opt/venv/bin/python

zfs:
  - name: immich_data
    mode: "0755"
  - name: immich_model_cache
    mode: "0755"

nullfs:
  - src: immich_data
    dst: /image/immich-server/data
  - src: immich_model_cache
    dst: /image/immich-server/cache

pkg:
  - skopeo

services: []
