userland: "15.0-RELEASE"

zfs:
  - name: zroot/jails/volumes/taulubot
    mountpoint: /usr/local/taulubot/photos

pkg:
  - python311
  - py311-pip
  - py311-setuptools
  - py311-build
  - py311-installer
  - py311-wheel
  - git
  - jpeg-turbo

services:
  - taulubot
