#!/bin/sh
set -e
if [ "$#" -ne 2 ]; then
    echo "Usage: describe [REPO_NAME] [DESCRIPTION]"
    echo "Note: quote the description if it contains spaces"
    exit 1
fi
if [ ! -d "$1.git" ]; then
    echo "Repository $1 does not exist"
    exit 1
fi
echo "$2" > "$1.git/description"
echo "Updated description for $1"
