userland: "15.1-RELEASE"

zfs:
  - name: leolalla_fi_data

nullfs:
  - src: leolalla_fi_data
    dst: /var/db/gdrive-photo-gallery

pkg_custom:
  - gdrive-photo-gallery

services:
  - gdrive_photo_gallery
