userland: "15.0-RELEASE"

zfs:
  - name: zroot/jails/volumes/leolalla_fi_data
    mountpoint: /var/db/gdrive-photo-gallery

pkg:
  - py312-sqlite3
  - py312-uv
  - py312-pillow
  - python

pkg_custom:
  - gdrive-photo-gallery

services:
  - gdrive_photo_gallery
