userland: "15.1-minimal-jail"

zfs:
  - name: irc_thelounge

nullfs:
  - src: irc_thelounge
    dst: /var/db/thelounge

pkg:
  # libexecinfo.so.1 needed by node
  - FreeBSD-libexecinfo

pkg_custom:
  - thelounge

services:
  - thelounge

rc_conf: |
  thelounge_user="root"
  thelounge_group="wheel"
