- import_role:
    name: jail
    tasks_from: jail_setup

- name: Deploy valkey.conf
  template:
    src: "{{ jail_role_dir }}/templates/valkey.conf.j2"
    dest: /usr/local/etc/valkey.conf
    owner: root
    group: valkey
    mode: "0640"
  notify: Restart valkey

- import_role:
    name: jail
    tasks_from: jail_launch
