- import_role:
    name: jail
    tasks_from: jail_setup

- name: Configure bind address
  lineinfile:
    path: /usr/local/etc/valkey.conf
    line: "bind * -::*"
    regexp: "^bind "
  notify: Restart valkey

- name: Configure protected-mode
  lineinfile:
    path: /usr/local/etc/valkey.conf
    line: "protected-mode yes"
    regexp: "^protected-mode"
  notify: Restart valkey

- name: Configure requirepass
  lineinfile:
    path: /usr/local/etc/valkey.conf
    line: "requirepass {{ valkey_password }}"
    regexp: "^requirepass"
  notify: Restart valkey

- import_role:
    name: jail
    tasks_from: jail_launch
