userland: "15.0-RELEASE"

nullfs:
  - src: /usr/local/jails/volumes/storage/docs
    dst: /mnt/docs
  - src: /usr/local/jails/volumes/storage/vault
    dst: /mnt/vault
  - src: /usr/local/jails/volumes/storage/jan-systems-2025-content
    dst: /mnt/jan-systems-2025-content
  - src: /usr/local/jails/volumes/storage/projects-ableton
    dst: /mnt/projects-ableton

zfs:
  - name: zroot/jails/volumes/syncthing_config
    mountpoint: /usr/local/etc/syncthing
    owner: "1001"
    group: "1001"

pkg:
  - syncthing

services:
  - syncthing
