userland: "15.1-RELEASE"

nullfs:
  - src: storage/docs
    dst: /mnt/docs
  - src: storage/vault
    dst: /mnt/vault
  - src: storage/jan-systems-2025-content
    dst: /mnt/jan-systems-2025-content
  - src: storage/projects-ableton
    dst: /mnt/projects-ableton

zfs:
  - name: syncthing_config
    owner: "1001"
    group: "1001"

nullfs:
  - src: syncthing_config
    dst: /usr/local/etc/syncthing

pkg:
  - syncthing

services:
  - syncthing
